### ISSUE TITLE
Create base16 schema

### ISSUE THREAD

**Issue by g8-dev** [laniusone/kyotonight.vim#14]
Hello!
I love this theme, its perfect!!
Thank you!!

Can you create a schema in base16 framework?
https://github.com/chriskempson/base16

I created for myself but is better if you can design your base16-theme for more consistence with your vim theme.

My theme kyotonight.yaml:
```yaml
# scheme: "kyotonight-"
# author: "https://github.com/shrikecode/kyotonight.vim/"
scheme: "kyotonight"
author: "shrikecode"
base00: "1a1b26"
base01: "292e42"
base02: "32344a"
base03: "33467c"
base04: "545c7e"
base05: "a9b1d6"
base06: "c0caf5"
base07: "e4e4e5"
base08: "f7768e"
base09: "9ece6a"
base0A: "e0af68"
base0B: "7aa2f7"
base0C: "ad8ee6"
base0D: "73daca"
base0E: "ff9e64"
base0F: "db4b4b"
```

**Comment by wmwnuk** [comment]
Sorry for the delay, I'm looking into this to make sure it's all nice, but your code looks good to me. But will let you know. I'm not very familiar with base16, so I need a moment, but it also seems pretty cool. :)

**Comment by wmwnuk** [comment]
Ok, I think I've got something right here, but I tested it only with base16-vim template. Can you take a look and maybe suggest changes? @guifuentes8 

```yaml
scheme: "kyotonight"
author: "shrikecode"
base00: "1a1b26"
base01: "292e42"
base02: "32344a"
base03: "565f89"
base04: "545c7e"
base05: "a9b1d6"
base06: "c0caf5"
base07: "b4f9f8"
base08: "f7768e"
base09: "bb9af7"
base0A: "e0af68"
base0B: "7aa2f7"
base0C: "ad8ee6"
base0D: "73daca"
base0E: "7dcfff"
base0F: "db4b4b"
```

I also think that to follow what base16 is doing, I will create a new repo for this scheme (so you don't get all of the vim stuff and extras if you just want the scheme to run with builder).
